-- Inserciones en la tabla TEACHER
INSERT INTO TEACHER (TEACHER_ID, TEACHER_NAME, LAST_NAME, PHONE_NUMBER, EMAIL)
VALUES (1, 'Carlos', 'Ramírez', 999888777, 'carlos.ramirez@example.com');

INSERT INTO TEACHER (TEACHER_ID, TEACHER_NAME, LAST_NAME, PHONE_NUMBER, EMAIL)
VALUES (2, 'Laura', 'López', 666777888, 'laura.lopez@example.com');

INSERT INTO TEACHER (TEACHER_ID, TEACHER_NAME, LAST_NAME, PHONE_NUMBER, EMAIL)
VALUES (3, 'Marta', 'García', 555666777, 'pedro.garcia@example.com');



-- Inserciones en la tabla STUDENT
INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, LAST_NAME, PHONE_NUMBER, EMAIL)
VALUES (1, 'Juan', 'Pérez', 123456789, 'juan.perez@example.com');

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, LAST_NAME, PHONE_NUMBER, EMAIL)
VALUES (2, 'Ana', 'Gómez', 987654321, 'ana.gomez@example.com');

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME, LAST_NAME, PHONE_NUMBER, EMAIL)
VALUES (3, 'Luis', 'Martínez', 555111222, 'luis.martinez@example.com');



-- Inserciones en la tabla COURSE
INSERT INTO COURSE (COURSE_ID, COURSE_NUMBER_ID, TEACHER_ID, COURSE_NAME, START_DATE, END_DATE, DEPARTAMENT_CODE)
VALUES (1, 'C001', 1, 'Curso de Matemáticas', '2023-01-01', '2023-05-31', 101);

INSERT INTO COURSE (COURSE_ID, COURSE_NUMBER_ID, TEACHER_ID, COURSE_NAME, START_DATE, END_DATE, DEPARTAMENT_CODE)
VALUES (2, 'C002', 2, 'Curso de Historia', '2023-02-15', '2023-06-30', 102);

INSERT INTO COURSE (COURSE_ID, COURSE_NUMBER_ID, TEACHER_ID, COURSE_NAME, START_DATE, END_DATE, DEPARTAMENT_CODE)
VALUES (3, 'C003', 1, 'Curso de Ciencias', '2023-03-10', '2023-07-15', 103);

